### ISSUE TITLE
recursive option

### ISSUE THREAD

**Issue by evs-as** [deibit/cansina#14]
it would be nice, if  you can add an optional parameter to scan recursive if a directory was found.
A suggestion could be a "depth" parameter. E.g. ```--depth 0``` for endless scan, ```--depth 1``` as default and so on.

[feature request]

**Comment by deibit** [comment]
A recursive option has been implemented but is not what @evs-as described. A more likely feature is coming: 'crawling' which may be combined with recursion or function as a separate feature by its own. Closing this as is on the roadmap.
