### ISSUE TITLE
show full path in result

### ISSUE THREAD

**Issue by evs-as** [deibit/cansina#15]
It would be a great pleasure if the tool get an optional parameter to show the full url's in the result list instant of the found directories. This could make it easier to work with it (e.g. copy&pase).

[feature request]

**Comment by jhaddix** [comment]
I 2nd this one too =)

**Comment by deibit** [comment]
Added in 0899dc5b6eb4176886f31f3e6e3a21b25da9d3e5 with option '--full-path'. It will prepend the handle+domain in the results.

Also, check 'utils/viewer.py' is designed to bring help managing the results.
