### ISSUE TITLE
Show time to complete and error count

### ISSUE THREAD

**Issue by jhaddix** [deibit/cansina#19]
Some useful info when doing unlinked content discovery:

Show time to complete based on list size and avg req per thread. Lets me know how long, avg, I can be waiting for a long list.

The number of errors lets me know if I have been blacklisted by something like Akamai.

**Comment by deibit** [comment]
An ETA timer has been implemented (pull and take it as a very alpha feature). An error control should be implemented in a future, meaning a complete control over unsatisfied entries in the list and the proper reason (network off, DNS issues, large timeout...)
