### ISSUE TITLE
Fix for bad handshake (SSL version too low)

### ISSUE THREAD

**Issue by sethsec** [deibit/cansina#21]
Error:
```("bad handshake: Error([('SSL routines', 'tls_process_server_hello', 'version too low')],)",)```

*Server in question only supports sslv3 and tlsv1

Solution: 
```sudo pip install -I --user pyopenssl```

Might want to drop pyopenssl in a requirements.txt file in the repo.  

Nice project. I just started checking it out!

**Comment by deibit** [comment]
Hi @sethsec I updated the "Install" with a modified command: requests[security] it should install the latest pyOpenSSL, cryptography and idna. It should bypass system's openssl in case it is an ancient version.

Please, let me know if this solves the issue. BTW, a requirements.txt will be added. Thanks for reporting.

**Comment by sethsec** [comment]
ahh.  You know what it was. I saw that you had that in the install, and I ran pip install requests[security]. It looks like it runs,  but didn't notice that it segfaults unless you use sudo if you are a non priv user.  

so user error for sure.  That said, maybe put sudo in front of the pip command in the readme. I don't think it hurts, but your call of course.

**Comment by deibit** [comment]
Certainly, adding 'sudo' in case of installation errors shouldn't hurt. +1.
