### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by Teicu** [deibit/cansina#24]
Hi 

can you help me please to fix this error: 

_/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py:7: UserWarning: Module chardet was already imported from /usr/local/lib/python2.7/dist-packages/chardet/__init__.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
  import pkg_resources
/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py:7: UserWarning: Module requests was already imported from /usr/local/lib/python2.7/dist-packages/requests/__init__.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path
  import pkg_resources
/usr/lib/python2.7/dist-packages/cryptography/hazmat/backends/__init__.py:7: UserWarning: Module urllib3 was already imported from /usr/local/lib/python2.7/dist-packages/urllib3/__init__.pyc, but /usr/lib/python2.7/dist-packages is being added to sys.path_ 

thank you

**Comment by deibit** [comment]
Sure, can you provide in which context you are getting those errors? Installing (which command), running (again, command and options). Please, provide Python version and operating system too.

Thanks.
