### ISSUE TITLE
Full path error

### ISSUE THREAD

**Issue by gwen001** [deibit/cansina#26]
Hi,

With the option `--full-path`, the printer displays a wrong path, example:

http://www.example.com/ -> http://www.example.com/test_dir
http://www.example.com/xxxx/ -> http://www.example.com/xxxx/xxxx/test_dir

The path segment of the full url is printed twice.

Fixed this way in `core/printer.py` line 119:
```
        # User wants to see full path
        if Console.show_full_path:
            t_encode = task.get_complete_target() 
        else:
            t_encode = target

        if sys.version_info[0] != 3:
            t_encode = t_encode.encode('utf-8')
```

Best regards,

Gwen

**Comment by deibit** [comment]
Thanks, fixed in https://github.com/deibit/cansina/commit/5a541ae8d2363982951977ed957ea7648f6d65ab
