### ISSUE TITLE
some page may cause encode error?

### ISSUE THREAD

**Issue by 500646** [deibit/cansina#27]
Hi,
can you help me to solve this error
[ 0%] -  2h15m41s - /global.mdbUnknown exception: 'ascii' codec can't encode characters in position 1-4: ordinal not in range(128)  File "./cansina.py", line 375, in <module>
    if not manager.get_a_task(visitors_alive):
  File "/home/test/cansina/core/dbmanager.py", line 57, in get_a_task
    Console.body(task)
  File "/home/test/cansina/core/printer.py", line 157, in body
    t_encode, content_type)
None
Finishing...Task took 11 seconds

**Comment by deibit** [comment]
Hi there. I need to gather some information before:

Are you using last version from the repository?
Which Python version?
May you bring me the offending payload file?

Thanks for reporting it!

**Comment by 500646** [comment]
thank you for reply.
yes, just download last version ,i use the python 2.7.12 on ubuntu,and when i switch to python 3 now,the error has gone.

**Comment by deibit** [comment]
Thanks for the reply. Yes, some files contains exotic characters Python2 and, my fault, I still struggle understanding how to deal with them. Usually Python3 is the straight solution.

**Comment by 500646** [comment]
ok,thank you for the awesome tool!!
