### ISSUE TITLE
recursive options is not not working  

### ISSUE THREAD

**Issue by triton89** [deibit/cansina#40]
Hi , 
is the recursive option has been implemented ?? it's not working if I use --recursive  no mater what i do it's simply not working. 
 python3 cansina.py --recursive -u target -p small.txt

**Comment by deibit** [comment]
[--recursive ](https://github.com/deibit/cansina/wiki/Wordlist-processing) is not meaning 'inspect for inner links and continue there' but having http://localhost/1/2/3 Cansina will recursively query from 1 to 3.

Closing this as I guess is what you were asking for. In case is not just let me know.
