### ISSUE TITLE
runing NO module import Inspector  ；）

### ISSUE THREAD

**Issue by MuTouRend** [deibit/cansina#8]

**Comment by deibit** [comment]
Yes, it is there for a future feature, as _crawler.py_ 

Regards.

**Comment by MuTouRend** [comment]
Can I understand that?
Currently the project can not be used
Or is there a better way to do it?
Thinks

**Comment by deibit** [comment]
Already fixed. Thanks @MuTouRend

**Comment by MuTouRend** [comment]
@_@    bang bang da
